/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
import 'gray-matter'
import { CreateDiscussionMutation } from '@blog/.vitepress/utils/github/graphql/github'

declare module 'gray-matter' {
  interface GrayMatterFile<I extends Input> {
    // 覆盖 data 的类型
    data: Frontmatter
  }
}

export interface Frontmatter {
  title?: string
  date?: string
  description?: string
  publish?: boolean
  tags?: string[]
  discussion?: CreateDiscussionMutation
}
